api/app/urls.py
import importlib

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.views.generic.base import TemplateView

from users.views import password_reset_redirect

from . import views

urlpatterns = [
    url(r"^api/v1/", include("api.urls.deprecated", namespace="api-deprecated")),
    url(r"^api/v1/", include("api.urls.v1", namespace="api-v1")),
    url(r"^admin/", admin.site.urls),
    url(r"^health", include("health_check.urls", namespace="health")),
    url(r"^version", views.version_info, name="version-info"),
    url(
        r"^sales-dashboard/",
        include("sales_dashboard.urls", namespace="sales_dashboard"),
    ),
    # this url is used to generate email content for the password reset workflow
    url(
        r"^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,"
        r"13}-[0-9A-Za-z]{1,20})/$",
        password_reset_redirect,
        name="password_reset_confirm",
    ),
    url(
        r"^config/project-overrides",
        views.project_overrides,
        name="project_overrides",
    ),
    path("processor/", include("task_processor.urls")),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        url(r"^__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

if settings.SAML_INSTALLED:
    urlpatterns.append(path("api/v1/auth/saml/", include("saml.urls")))

if settings.WORKFLOWS_LOGIC_INSTALLED:
    module_path = settings.WORKFLOWS_LOGIC_MODULE_PATH
    workflow_views = importlib.import_module(f"{module_path}.views")
    urlpatterns.extend(
        [
            path("api/v1/features/workflows/", include(f"{module_path}.urls")),
            path(
                "api/v1/environments/<str:environment_api_key>/create-change-request/",
                workflow_views.create_change_request,
                name="create-change-request",
            ),
            path(
                "api/v1/environments/<str:environment_api_key>/list-change-requests/",
                workflow_views.list_change_requests,
                name="list-change-requests",
            ),
        ]
    )

if settings.SERVE_FE_ASSETS:
    # add route to serve FE assets for any unrecognised paths
    urlpatterns.append(url(r"^.*$", views.index, name="index"))

api/organisations/urls.py
from app_analytics.views import (
    get_usage_data_total_count_view,
    get_usage_data_view,
)
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from rest_framework_nested import routers

from api_keys.views import MasterAPIKeyViewSet
from audit.views import OrganisationAuditLogViewSet
from metadata.views import MetaDataModelFieldViewSet
from organisations.views import OrganisationWebhookViewSet
from users.views import (
    FFAdminUserViewSet,
    UserPermissionGroupViewSet,
    make_user_group_admin,
    remove_user_as_group_admin,
)

from . import views
from .invites.views import InviteLinkViewSet, InviteViewSet
from .permissions.views import (
    UserOrganisationPermissionViewSet,
    UserPermissionGroupOrganisationPermissionViewSet,
)

router = routers.DefaultRouter()
router.register(r"", views.OrganisationViewSet, basename="organisation")

organisations_router = routers.NestedSimpleRouter(router, r"", lookup="organisation")
organisations_router.register(
    r"invites", InviteViewSet, basename="organisation-invites"
)
organisations_router.register(
    r"metadata-model-fields",
    MetaDataModelFieldViewSet,
    basename="metadata-model-fields",
)
organisations_router.register(
    r"invite-links", InviteLinkViewSet, basename="organisation-invite-links"
)
organisations_router.register(
    r"users", FFAdminUserViewSet, basename="organisation-users"
)
organisations_router.register(
    r"groups", UserPermissionGroupViewSet, basename="organisation-groups"
)
organisations_router.register(
    r"webhooks", OrganisationWebhookViewSet, basename="organisation-webhooks"
)
organisations_router.register(
    r"master-api-keys", MasterAPIKeyViewSet, basename="organisation-master-api-keys"
)
organisations_router.register(
    "user-permissions",
    UserOrganisationPermissionViewSet,
    basename="organisation-user-permission",
)
organisations_router.register(
    "user-group-permissions",
    UserPermissionGroupOrganisationPermissionViewSet,
    basename="organisation-user-group-permission",
)

organisations_router.register(
    "audit", OrganisationAuditLogViewSet, basename="audit-log"
)

app_name = "organisations"


urlpatterns = [
    url(r"^", include(router.urls)),
    url(r"^", include(organisations_router.urls)),
    path(
        "<int:organisation_pk>/usage-data/",
        get_usage_data_view,
        name="usage-data",
    ),
    path(
        "<int:organisation_pk>/usage-data/total-count/",
        get_usage_data_total_count_view,
        name="usage-data-total-count",
    ),
    path(
        "<int:organisation_pk>/groups/<int:group_pk>/users/<int:user_pk>/make-admin",
        make_user_group_admin,
        name="make-user-group-admin",
    ),
    path(
        "<int:organisation_pk>/groups/<int:group_pk>/users/<int:user_pk>/remove-admin",
        remove_user_as_group_admin,
        name="remove-user-group-admin",
    ),
]

if settings.IS_RBAC_INSTALLED:
    from rbac.views import (
        GroupRoleViewSet,
        MasterAPIKeyRoleViewSet,
        RoleEnvironmentPermissionsViewSet,
        RoleOrganisationPermissionViewSet,
        RoleProjectPermissionsViewSet,
        RolesByGroupViewSet,
        RolesbyMasterAPIPrefixViewSet,
        RolesByUserViewSet,
        RoleViewSet,
        UserRoleViewSet,
    )

    organisations_router.register("roles", RoleViewSet, basename="organisation-roles")
    nested_user_roles_routes = routers.NestedSimpleRouter(
        parent_router=organisations_router, parent_prefix=r"users", lookup="user"
    )

    nested_api_key_roles_routes = routers.NestedSimpleRouter(
        parent_router=organisations_router,
        parent_prefix=r"master-api-keys",
        lookup="api_key",
    )

    nested_group_roles_routes = routers.NestedSimpleRouter(
        parent_router=organisations_router, parent_prefix=r"groups", lookup="group"
    )

    nested_roles_router = routers.NestedSimpleRouter(
        organisations_router, r"roles", lookup="role"
    )
    nested_user_roles_routes.register(
        prefix="roles",
        viewset=RolesByUserViewSet,
        basename="role-users",
    )
    nested_api_key_roles_routes.register(
        prefix="roles",
        viewset=RolesbyMasterAPIPrefixViewSet,
        basename="role-api-keys",
    )
    nested_group_roles_routes.register(
        prefix="roles",
        viewset=RolesByGroupViewSet,
        basename="role-groups",
    )
    nested_roles_router.register(
        "environments-permissions",
        RoleEnvironmentPermissionsViewSet,
        basename="roles-environments-permissions",
    )
    nested_roles_router.register(
        "projects-permissions",
        RoleProjectPermissionsViewSet,
        basename="roles-projects-permissions",
    )
    nested_roles_router.register(
        "organisation-permissions",
        RoleOrganisationPermissionViewSet,
        basename="roles-organisations-permissions",
    )
    nested_roles_router.register("groups", GroupRoleViewSet, basename="group-roles")
    nested_roles_router.register("users", UserRoleViewSet, basename="user-roles")
    nested_roles_router.register(
        "master-api-keys", MasterAPIKeyRoleViewSet, basename="master-api-key-roles"
    )
    urlpatterns.extend(
        [
            url(r"^", include(organisations_router.urls)),
            url(r"^", include(nested_roles_router.urls)),
            url(r"^", include(nested_user_roles_routes.urls)),
            url(r"^", include(nested_api_key_roles_routes.urls)),
            url(r"^", include(nested_group_roles_routes.urls)),
        ]
    )

api/sales_dashboard/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from . import views

app_name = "sales_dashboard"


urlpatterns = [
    path("", staff_member_required(views.OrganisationList.as_view()), name="index"),
    path(
        "organisations/<int:organisation_id>",
        views.organisation_info,
        name="organisation_info",
    ),
    path(
        "organisations/<int:organisation_id>/update_seats",
        views.update_seats,
        name="update_seats",
    ),
    path(
        "organisations/<int:organisation_id>/organisation_start_trial",
        views.organisation_start_trial,
        name="organisation_start_trial",
    ),
    path(
        "organisations/<int:organisation_id>/organisation_end_trial",
        views.organisation_end_trial,
        name="organisation_end_trial",
    ),
    path(
        "organisations/<int:project_id>/migrate_identities",
        views.migrate_identities_to_edge,
        name="migrate_identities",
    ),
    path(
        "organisations/<int:organisation_id>/update_max_api_calls",
        views.update_max_api_calls,
        name="update_max_api_calls",
    ),
    path(
        "email-usage/",
        staff_member_required(views.EmailUsage.as_view()),
        name="email-usage",
    ),
    path(
        "organisations/<int:organisation_id>/download_org_data",
        views.download_org_data,
        name="download-org-data",
    ),
    path(
        "update-organisation-subscription-information-influx-cache",
        views.trigger_update_organisation_subscription_information_influx_cache,
        name="update-organisation-subscription-information-influx-cache",
    ),
    path(
        "update-organisation-subscription-information-cache",
        views.trigger_update_organisation_subscription_information_cache,
        name="update-organisation-subscription-information-cache",
    ),
    path(
        "update-chargebee-cache",
        views.trigger_update_chargebee_caches,
        name="update-chargebee-cache",
    ),
]

api/organisations/invites/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.decorators import action, api_view
from rest_framework.exceptions import PermissionDenied
from rest_framework.mixins import (
    CreateModelMixin,
    DestroyModelMixin,
    ListModelMixin,
    RetrieveModelMixin,
)
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.throttling import ScopedRateThrottle
from rest_framework.viewsets import GenericViewSet

from organisations.invites.exceptions import InviteExpiredError
from organisations.invites.models import Invite, InviteLink
from organisations.invites.serializers import (
    InviteLinkSerializer,
    InviteListSerializer,
)
from organisations.models import Organisation
from organisations.permissions.permissions import (
    NestedOrganisationEntityPermission,
)
from organisations.serializers import (
    InviteSerializer,
    OrganisationSerializerFull,
)
from organisations.subscriptions.exceptions import (
    SubscriptionDoesNotSupportSeatUpgrade,
)
from users.exceptions import InvalidInviteError


@api_view(["POST"])
def join_organisation_from_email(request, hash):
    invite = get_object_or_404(Invite, hash=hash)
    try:
        request.user.join_organisation_from_invite_email(invite)

    except InvalidInviteError as e:
        error_data = {"detail": str(e)}
        return Response(data=error_data, status=status.HTTP_400_BAD_REQUEST)

    return Response(
        OrganisationSerializerFull(
            invite.organisation, context={"request": request}
        ).data,
        status=status.HTTP_200_OK,
    )


@api_view(["POST"])
def join_organisation_from_link(request, hash):
    if settings.DISABLE_INVITE_LINKS:
        raise PermissionDenied("Invite links are disabled.")

    invite = get_object_or_404(InviteLink, hash=hash)

    if invite.is_expired:
        raise InviteExpiredError()

    request.user.join_organisation_from_invite_link(invite)

    return Response(
        OrganisationSerializerFull(
            invite.organisation, context={"request": request}
        ).data,
        status=status.HTTP_200_OK,
    )


class InviteLinkViewSet(
    ListModelMixin,
    CreateModelMixin,
    DestroyModelMixin,
    GenericViewSet,
):
    permission_classes = [IsAuthenticated, NestedOrganisationEntityPermission]
    serializer_class = InviteLinkSerializer
    pagination_class = None

    def get_queryset(self):
        if getattr(self, "swagger_fake_view", False):
            return InviteLink.objects.none()

        organisation_pk = self.kwargs.get("organisation_pk")
        user = self.request.user
        organisation = Organisation.objects.get(id=organisation_pk)

        if (
            settings.ENABLE_CHARGEBEE
            and organisation.over_plan_seats_limit(additional_seats=1)
            and not organisation.is_auto_seat_upgrade_available()
        ):
            raise SubscriptionDoesNotSupportSeatUpgrade()

        return InviteLink.objects.filter(
            organisation__in=user.organisations.all()
        ).filter(organisation__pk=organisation_pk)

    def perform_create(self, serializer):
        serializer.save(organisation_id=self.kwargs.get("organisation_pk"))


class InviteViewSet(
    ListModelMixin,
    CreateModelMixin,
    DestroyModelMixin,
    GenericViewSet,
    RetrieveModelMixin,
):
    permission_classes = [IsAuthenticated, NestedOrganisationEntityPermission]
    throttle_scope = "invite"

    def get_serializer_class(self):
        return {
            "list": InviteListSerializer,
            "retrieve": InviteListSerializer,
            "create": InviteSerializer,
        }.get(self.action, InviteListSerializer)

    def get_queryset(self):
        if getattr(self, "swagger_fake_view", False):
            return Invite.objects.none()

        organisation_pk = self.kwargs.get("organisation_pk")
        user = self.request.user

        return Invite.objects.filter(organisation__in=user.organisations.all()).filter(
            organisation__id=organisation_pk
        )

    @action(detail=True, methods=["POST"], throttle_classes=[ScopedRateThrottle])
    def resend(self, request, organisation_pk, pk):
        invite = self.get_object()
        invite.send_invite_mail()
        return Response(status=status.HTTP_200_OK)

    def perform_create(self, serializer):
        organisation = Organisation.objects.get(id=self.kwargs.get("organisation_pk"))
        subscription_metadata = organisation.subscription.get_subscription_metadata()

        if (
            len(settings.AUTO_SEAT_UPGRADE_PLANS) > 0
            and organisation.num_seats >= subscription_metadata.seats
            and not organisation.subscription.can_auto_upgrade_seats
        ):
            raise SubscriptionDoesNotSupportSeatUpgrade()

        serializer.save(
            organisation_id=self.kwargs.get("organisation_pk"),
            invited_by=self.request.user,
        )

api/organisations/permissions/views.py
from __future__ import unicode_literals

from rest_framework import mixins, viewsets
from rest_framework.permissions import IsAuthenticated

from organisations.permissions.models import (
    UserOrganisationPermission,
    UserPermissionGroupOrganisationPermission,
)
from organisations.permissions.permissions import (
    NestedOrganisationEntityPermission,
)
from organisations.permissions.serializers import (
    UserOrganisationPermissionListSerializer,
    UserOrganisationPermissionUpdateCreateSerializer,
    UserPermissionGroupOrganisationPermissionListSerializer,
    UserPermissionGroupOrganisationPermissionUpdateCreateSerializer,
)


class BaseOrganisationPermissionViewSet(
    mixins.ListModelMixin,
    mixins.CreateModelMixin,
    mixins.DestroyModelMixin,
    mixins.UpdateModelMixin,
    viewsets.GenericViewSet,
):
    pagination_class = None
    permission_classes = [IsAuthenticated, NestedOrganisationEntityPermission]

    def perform_create(self, serializer):
        serializer.save(organisation_id=self.kwargs.get("organisation_pk"))


class UserOrganisationPermissionViewSet(BaseOrganisationPermissionViewSet):
    filterset_fields = ["user"]

    def get_queryset(self):
        return UserOrganisationPermission.objects.select_related("user").filter(
            organisation_id=self.kwargs.get("organisation_pk")
        )

    def get_serializer_class(self):
        return {"list": UserOrganisationPermissionListSerializer}.get(
            self.action, UserOrganisationPermissionUpdateCreateSerializer
        )


class UserPermissionGroupOrganisationPermissionViewSet(
    BaseOrganisationPermissionViewSet
):
    filterset_fields = ["group"]

    def get_queryset(self):
        return UserPermissionGroupOrganisationPermission.objects.select_related(
            "group"
        ).filter(organisation_id=self.kwargs.get("organisation_pk"))

    def get_serializer_class(self):
        return {"list": UserPermissionGroupOrganisationPermissionListSerializer}.get(
            self.action, UserPermissionGroupOrganisationPermissionUpdateCreateSerializer
        )

api/sales_dashboard/templates/sales_dashboard/base.html
{% load sales_dashboard_extras %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'sales_dashboard/css/bootstrap.min.css' %}"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.css">
    <title>Flagsmith Sales Dashboard</title>
  </head>
  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="/sales-dashboard/">Flagsmith</a>
      <form method="get" action="{% url 'sales_dashboard:index' %}" class="form-inline w-100">
        {% csrf_token %}
        <input class="form-control mr-sm-2 w-100=" type="search" placeholder="Search" aria-label="Search" name="search" value="{{ search }}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{% url 'admin:logout' %}">Sign out</a>
        </li>
      </ul>
    </nav>
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

api/sales_dashboard/templates/sales_dashboard/email-usage.html
{% extends "sales_dashboard/base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {% include "sales_dashboard/nav.html" %}

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <form method="post" action="{% url 'sales_dashboard:email-usage' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit"/>
            </form>
        </main>
    </div>
</div>
{% endblock %}

api/sales_dashboard/templates/sales_dashboard/organisation.html
{% extends "sales_dashboard/base.html" %}
{% load humanize %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {% include "sales_dashboard/nav.html" %}

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2 float-left">
                    Organisation: <strong>{{organisation.name}}</strong>
                    - Plan: <strong>{{ organisation.subscription.plan|default:"Free"}}</strong>
                    {% if organisation.has_paid_subscription and not organisation.is_paid %}<span class="badge badge-danger">Subscription Cancelled</button>{% endif %}
                </h1>
                <div class="float-right"><a href="/admin/organisations/organisation/{{organisation.id}}/change">Django Admin</a></div>
                <div class="float-right">
                    <form method="POST" action="{% url 'sales_dashboard:download-org-data' organisation.id %}">
                        {% csrf_token %}
                        <input type="submit" value="Download Org Data">
                    </form>
                </div>
            </div>
            <div class="clearfix"></div>

            <h2>API Calls</h2>
            <table class="table table-striped table-sm">
                <thead class="thead-dark">
                    <tr>
                        <th>24h</th>
                        <th>7d</th>
                        <th>30d</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{api_calls.24h|intcomma}}</td>
                        <td>{{api_calls.7d|intcomma}}</td>
                        <td>{{api_calls.30d|intcomma}}</td>
                        </tr>
                </tbody>
            </table>

            <h2>
                Subscription
                {%if chargebee_email%} - <a href="mailto:{{ chargebee_email }}">{{ chargebee_email }}</a>{% endif %}
            </h2>
            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <thead class="thead-dark">
                        <tr>
                            <th>Start</th>
                            <th>End</th>
                            <th>CB Customer ID</th>
                            <th>CB Subscription Id</th>
                            <th>Plan</th>
                            <th>Max Seats</th>
                            <th>Max API calls</th>
                            <th>Max Projects</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ organisation.subscription.subscription_date|date:"M d, Y" }}</td>
                            <td>{{ organisation.subscription.cancellation_date|date:"M d, Y" }}</td>
                            <td>
                                {% if organisation.subscription.payment_method == "CHARGEBEE" %}
                                    <a target="_blank" href="https://flagsmith.chargebee.com/customers?view_code=all&Customers.search={{ organisation.subscription.customer_id }}">{{ organisation.subscription.customer_id }}</a>
                                {% endif %}
                            </td>
                            <td>
                                {% if organisation.subscription.payment_method == "CHARGEBEE" %}
                                    <a target="_blank" href="https://flagsmith.chargebee.com/subscriptions?view_code=all&Subscriptions.search={{ organisation.subscription.subscription_id }}">{{ organisation.subscription.subscription_id }}</a>
                                {% endif %}
                            </td>
                            <td>{{ organisation.subscription.plan }}</td>
                            <td>{{ max_seats }}</td>
                            <td>{{ max_api_calls|intcomma }}</td>
                            <td>{{ max_projects|default_if_none:"No limit configured" }}</td>
                        </tr>
                    </tbody>
                </table>
                {%if organisation.subscription.is_in_trial %}
                    <form action="{% url 'sales_dashboard:organisation_end_trial' organisation.id %}" method="post" class="form-inline float-right">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary mb-2">End Trial</button>
                    </form>
                {% else %}
                    <form action="{% url 'sales_dashboard:organisation_start_trial' organisation.id %}" method="post" class="form-inline float-right">
                        {% csrf_token %}
                        <label class="sr-only" for="trialSeats">Seats</label>
                        <input type="text" class="form-control mb-2 mr-sm-2" id="max_seats" name="max_seats" placeholder="Seats">
                        <label class="sr-only" for="trialApiCalls">API Calls</label>
                        <input type="text" class="form-control mb-2 mr-sm-2" id="max_api_calls" name="max_api_calls" placeholder="API Calls">
                        <button type="submit" class="btn btn-primary mb-2">Start Trial</button>
                    </form>
                {% endif %}
            </div>

            <h2>Projects</h2>
            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Created</th>
                            <th>Name</th>
                            <th>Environments</th>
                            <th>Features</th>
                            <th>Segments</th>
                            <th>Dynamo DB Enabled</th>
                            <th>Identity Count</th>
                            <th>Identity Migration Status</th>
                            <th>Migrate Identity</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for project in organisation.projects.all %}

                        <tr>
                            <td>{{project.id}}</td>
                            <td>{{project.created_date|date:"M d, Y"}}</td>
                            <td>{{project.name}}</td>
                            <td>{{project.environments.all.count}}</td>
                            <td>{{project.features.all.count}}</td>
                            <td>{{project.segments.all.count}}</td>
                            <td>{{project.enable_dynamo_db}}</td>
                            <td>{{identity_count_dict|get_item:project.id|intcomma}}</td>
                            <td>{{identity_migration_status_dict|get_item:project.id}}</td>
                            <td>
                            <form method="POST" class="form-inline" action="{% url 'sales_dashboard:migrate_identities' project.id %}">
                                {% csrf_token %}
                                <input value="migrate identities" {% if identity_migration_status_dict|get_item:project.id != "MIGRATION_NOT_STARTED" %} {{'disabled'}} {% endif %} type="submit"/>
                            </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <h2>Seats in Use: <strong>{{ organisation.users.count }}</strong></h2>
            <h3><a href="mailto:{% for user in organisation.users.all %}{{user.email}},{% endfor %}">Mail All Users</a></h3>
            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email Address</th>
                            <th>Date Registered</th>
                            <th>Last Logged In</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in organisation.users.all %}
                        <tr>
                            <td>{{ user.id }}</td>
                            <td>{{ user.first_name}}</td>
                            <td><a href="mailto:{{user.email}}">{{user.email}}</a></td>
                            <td>{{ user.date_joined }}</td>
                            <td>{{ user.last_login }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
                <div class="container">
                    <form action="{% url 'sales_dashboard:organisation_info' organisation.id %}" method="get" class="form-inline float-right">
                        <label for="date-range">Days History: </label>
                          <select name="date_range" id="date-range" class="custom-select m-1">
                            <option value="30d" {% if date_range == "30d" %}selected{% endif %}>30d</option>
                            <option value="90d" {% if date_range == "90d" %}selected{% endif %}>90d</option>
                            <option value="180d" {% if date_range == "180d" %}selected{% endif %}>180d</option>
                            <option value="365d" {% if date_range == "365d" %}selected{% endif %}>365d</option>
                          </select>
                          <button type="submit" class="btn btn-primary m-1">Apply</button>
                        </form>
                    <canvas id="examChart"></canvas>
                </div>
            </div>
        </main>
    </div>
</div>

{% endblock %}

{% block script %}
<script>
var ctx = document.getElementById("examChart").getContext("2d");
var myChart = new Chart(ctx, {
  type: 'bar',
  data: {
    labels: {{labels}},
    datasets: [
      {
        label: 'Flags',
        data: {{flags}},
        backgroundColor: '#D6E9C6',
      },
      {
        label: 'Identities',
        data: {{identities}},
        backgroundColor: '#FAEBCC',
      },
      {
        label: 'Traits',
        data: {{traits}},
        backgroundColor: '#EBCCD1',
      },
      {
        label: 'Environment Documents',
        data: {{environment_documents}},
        backgroundColor: '#368BD1',
      }
    ]
  },
  options: {
    scales: {
      xAxes: [{ stacked: true }],
      yAxes: [{ stacked: true }]
    }
  }
});
</script>
{% endblock %}